HotKeys:
   'F1': [ MyWritings ]
#  'F2': [ MyReadingsEbooks ]
#  'F3': [ SourceCodeProjects ]
  'F4': [ Chromebookmark1 ]
#  'ctrl F1': [ null1 ]

# TODO:
# Settings:
#   BlackTheme: true
#   fontSize: 32

Chromebookmark1:
  type: ChromeBookmarkPlugin
  filename: '~/.config/google-chrome/Default/Bookmarks'
  # scope: 'Sites/Download'
  scope: ''

MyWritings:
  type: FileSearchPlugin
  scanDirectories: ['~/Dropbox/2Writing']

MyReadingsEbooks:
  type: FileSearchPlugin
  scanDirectories: ['~/Dropbox/1Reading', '~/Dropbox/eBook', '~/eBook']

SourceCodeProjects:
  type: FileSearchPlugin
  scanDirectories: ['~/source/caine/']

MusicAudioBooks:
  type: FileSearchPlugin
  scanDirectories: ['~/Music/']

null1:
  type: NullPlugin
