/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_caine_ui_ActivateWindowJni */

#ifndef _Included_com_caine_ui_ActivateWindowJni
#define _Included_com_caine_ui_ActivateWindowJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_caine_ui_ActivateWindowJni
 * Method:    activateWindow
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_caine_ui_ActivateWindowJni_activateWindow
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
